set -g mouse on

# custom spiliting window
bind _ split-window -h
bind - split-window -v   
set -g status-keys vi
set -g status-style fg=white,bg=black
bind-key -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel 'xclip -se c -i'
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel 'xclip -se c -i'
bind-key -T copy-mode-vi y send-keys -X rectangle-toggle
unbind -T copy-mode-vi Enter
bind P paste-buffer
bind-key -T copy-mode-vi v send-keys -X begin-selection

set -g default-terminal "screen-256color"
source "/usr/share/powerline/bindings/tmux/powerline.conf"

